### ISSUE TITLE
[Bug]: tap still at 2.0.3

### ISSUE THREAD

**Issue by Okeanos** [russellbanks/homebrew-tap#1]
**Describe the bug**

The latest released version with important fixes for macOS is 2.0.4, however, the tap is still pointing at 2.0.3.

**To Reproduce**

N/A

**Expected behavior**

The latest version is available.

**Comment by vedantmgoyal9** [comment]
- https://github.com/russellbanks/Komac/pull/441 needs to be merged in order to automatically update homebrew-tap.

**Comment by russellbanks** [comment]
@vedantmgoyal2009 Can you manually update the homebrew tap for 2.0.4 please? I'll merge https://github.com/russellbanks/Komac/pull/441 to get this updated automatically for future releases.

**Comment by vedantmgoyal9** [comment]
Done!

**Comment by Okeanos** [comment]
That was quick, thanks a lot 😍
